### ISSUE TITLE
Usage help

### ISSUE THREAD

**Issue by Csega** [AsmaAfzal/octave_workspace#1]
Hi!

I am a novice Octave user, so please forgive me if I'm asking something totally trivial. I'd like to use the nlinfit function from your repository. I downloaded all, created a PKG_ADD file in the directory (and added the line: **all_stat_opts** ("nlinfit");), added the whole directory to the Octave path, and when I try to run runnlinfit.m, I got the following error:

``` octave
error: 'nonlin_curvefit' undefined near line 127 column 21
error: called from
    nlinfit at line 127 column 18
    runnlinfit at line 9 column 23
```

What am I doing wrong? Could you please write a short guide, how to use these routines?

Thanks in advance! :)

Cheers!
Csega

**Comment by AsmaAfzal** [comment]
Hello,

Seems like you have not loaded the optim package.

run this command 
pkg list
if you see optim then type 
pkg load optim

if you dont see optim package then run this file.

octave-4.0.0\src\build_packages.m

and load the optim package and try running your code.

Regards,
Asma.

**Comment by Csega** [comment]
Thanks for the fast answer.

I loaded the optim package, but now I get the following error message:

``` octave
warning: unrecognized option: DerivStep
warning: called from
    statget at line 45 column 5
    nlinfit at line 105 column 15
    runnlinfit at line 15 column 23
warning: unrecognized option: TolFun
warning: unrecognized option: MaxIter
warning: optimset: unrecognized option: FinDiffRelStep
```

What could be the problem?

**Comment by AsmaAfzal** [comment]
These warnings will be removed when the function will be integrated into the optim package. It should not affect your results.
For now, you can run '**all_stat_opts**(stat_opts)' to avoid these warnings.

**Comment by Csega** [comment]
Thanks, it seems to work now. :)
